1:
  avdd:
  - 0x20
  - 0x1e
  - 0x1e
  - 0x1f
  - 0x1e
  - 0x1f
  - 0x1f
  - 0x1d
  dvdd:
  - 0x1f
  - 0x1f
  - 0x1d
  - 0x1e
  - 0x1c
  - 0x1e
  - 0x1e
  - 0x1e
2:
  avdd:
  - 0x1b
  - 0x1d
  - 0x20
  - 0x1e
  - 0x1f
  - 0x1f
  - 0x1e
  - 0x1b
  dvdd:
  - 0x1b
  - 0x1d
  - 0x1b
  - 0x1c
  - 0x21
  - 0x20
  - 0x1d
  - 0x1d
