1:
  avdd:
  - 0x18
  - 0x18
  - 0x1a
  - 0x19
  - 0x1d
  - 0x1e
  - 0x1c
  - 0x1c
  dvdd:
  - 0x17
  - 0x16
  - 0x1c
  - 0x1a
  - 0x1f
  - 0x1b
  - 0x1b
  - 0x1a
2:
  avdd:
  - 0x16
  - 0x16
  - 0x20
  - 0x1f
  - 0x17
  - 0x18
  - 0x1f
  - 0x1e
  dvdd:
  - 0x13
  - 0x17
  - 0x1d
  - 0x20
  - 0x17
  - 0x17
  - 0x1e
  - 0x1f
