1:
  avdd:
  - 0x22
  - 0x1f
  - 0x21
  - 0x20
  - 0x1a
  - 0x18
  - 0x1c
  - 0x1b
  dvdd:
  - 0x23
  - 0x22
  - 0x1f
  - 0x21
  - 0x19
  - 0x1c
  - 0x1d
  - 0x1c
2:
  avdd:
  - 0x1a
  - 0x1c
  - 0x1a
  - 0x1e
  - 0x1d
  - 0x1b
  - 0x1c
  - 0x1c
  dvdd:
  - 0x1d
  - 0x1a
  - 0x1a
  - 0x1a
  - 0x1c
  - 0x1c
  - 0x1d
  - 0x1b
