1:
  avdd:
  - 0x22
  - 0x23
  - 0x1e
  - 0x1f
  - 0x23
  - 0x1e
  - 0x1c
  - 0x1c
  dvdd:
  - 0x20
  - 0x21
  - 0x1f
  - 0x21
  - 0x20
  - 0x1e
  - 0x1d
  - 0x1f
2:
  avdd:
  - 0x22
  - 0x1f
  - 0x1f
  - 0x1e
  - 0x20
  - 0x1f
  - 0x1f
  - 0x21
  dvdd:
  - 0x20
  - 0x20
  - 0x1e
  - 0x1e
  - 0x20
  - 0x1f
  - 0x20
  - 0x21
