1:
  avdd:
  - 0x1c
  - 0x1b
  - 0x20
  - 0x1e
  - 0x1a
  - 0x1e
  - 0x1b
  - 0x1f
  dvdd:
  - 0x1a
  - 0x1d
  - 0x20
  - 0x1e
  - 0x1c
  - 0x1d
  - 0x1e
  - 0x1c
2:
  avdd:
  - 0x1f
  - 0x21
  - 0x15
  - 0x15
  - 0x20
  - 0x21
  - 0x1d
  - 0x22
  dvdd:
  - 0x1e
  - 0x20
  - 0x17
  - 0x18
  - 0x1f
  - 0x1d
  - 0x1f
  - 0x22
