1:
  avdd:
  - 0x1d
  - 0x20
  - 0x1c
  - 0x1d
  - 0x1d
  - 0x1c
  - 0x1d
  - 0x1e
  dvdd:
  - 0x1e
  - 0x1d
  - 0x1d
  - 0x1c
  - 0x1c
  - 0x1a
  - 0x1e
  - 0x20
2:
  avdd:
  - 0x1c
  - 0x1d
  - 0x1a
  - 0x1c
  - 0x1c
  - 0x1c
  - 0x20
  - 0x1e
  dvdd:
  - 0x1d
  - 0x1c
  - 0x1a
  - 0x1d
  - 0x1d
  - 0x1c
  - 0x1d
  - 0x1b
