1:
  avdd:
  - 0x20
  - 0x21
  - 0x1e
  - 0x1e
  - 0x13
  - 0x14
  - 0x1e
  - 0x1f
  dvdd:
  - 0x20
  - 0x22
  - 0x1f
  - 0x20
  - 0x16
  - 0x16
  - 0x1e
  - 0x20
2:
  avdd:
  - 0x1d
  - 0x1d
  - 0x18
  - 0x1a
  - 0x1f
  - 0x21
  - 0x1c
  - 0x1e
  dvdd:
  - 0x1e
  - 0x1c
  - 0x15
  - 0x18
  - 0x1f
  - 0x21
  - 0x1c
  - 0x1b
