1:
  avdd:
  - 0x1d
  - 0x1d
  - 0x18
  - 0x17
  - 0x1a
  - 0x1c
  - 0x1a
  - 0x1d
  dvdd:
  - 0x1c
  - 0x1b
  - 0x19
  - 0x1a
  - 0x1e
  - 0x1c
  - 0x1b
  - 0x1e
2:
  avdd:
  - 0x17
  - 0x1c
  - 0x1a
  - 0x1c
  - 0x1c
  - 0x1c
  - 0x1b
  - 0x1d
  dvdd:
  - 0x1a
  - 0x1a
  - 0x1d
  - 0x1b
  - 0x1a
  - 0x1b
  - 0x1a
  - 0x1a
