# Configuration file for the testbench_flx1.py script.
#
# To modify this for a different local setup:
# copy to a file called "<filename>_local.yml" and modify that one
# The <filename>.py script will first look for the "..local.." file. If that
# isn't found it reads this file instead
#

# RU main version number (e.g. 2 for RUv2.1)
RU_MAIN_REVISION : 2
# RU minor version number (e.g. 1 for RUv2.1)
RU_MINOR_REVISION : 1
# Transition board version
RU_TRANSITION_BOARD_VERSION : V2_5
# see power_unit.py for choices
POWER_BOARD_VERSION : PRODUCTION
# POWER_BOARD_FILTER_50HZ_AC_POWER_MAINS_FREQUENCY : False for US
POWER_BOARD_FILTER_50HZ_AC_POWER_MAINS_FREQUENCY : False
# Hostname of the machine
HOSTNAME : "mvtx-flx1.sphenix.bnl.gov"
# CRU type (O2, RUv0, NONE) or FLX for MVTX
CRU_TYPE : FLX
CHECK_CRU_HASH : True
EXPECTED_CRU_GITHASH : 0x3C46BEB5
# CANbus setup: set to True for operating with the CANbus (don't forget to set CRU_type to None!)
# Set to False to avoid using the CANbus
USE_CAN_COMM : False
# If True runs with USB connection to RDO (Requires CruType to be NONE)
USE_RDO_USB : False
# Serial number of the CRU (string)
# (Not used in MVTX, keep for compatibility. For MVTX we use felix_card 0 by default.
CRU_SN : "0000"
# list of GBT links used for SWT (key) and for data/trigger (value)
# Write None if only SWT is used
# Write [gbtx1,gbtx2,trg] if is used, trailing None can be omitted
LINK_DICT :
  0:  [1,2,2]
  3:  [4,5,5]
  6:  [7,8,8]
  9:  [10,11,11]
  12: [13,14,14]
  15: [16,17,17]
  18: [19,20,20]
  21: [22,23,23]
# Layer definition
LAYER : INNER

# offset resistance. 3.4 for 4.5m OB cables. +/- 0.1 for every 1m of cable.
POWERUNIT_RESISTANCE_OFFSET_PT100 : 2.0
# Hostname of machine running the LTU service
# Not used by MVTX project
LTU_HOSTNAME : "None"
# Crate
SUBRACK : "MVTX_FLX1"
